WIP: Settings API
bettersg/saylah-v2 pull request #10
Opened 2024-07-20 09:48 UTC by rayasamhr

2024-07-20 12:57 UTC, prakashelango requested changes
Unsure about html and scss changes being included.

2024-07-20 12:57 UTC, prakashelango commented on saylah-v2-be/controller/settings_controller.js
> +async function saveSettingsInDatabase(userId, language, output, theme) {
can we move this to an object? instead of multiple params

2024-07-20 12:57 UTC, prakashelango commented on saylah-v2-be/models/settings.js
> +    "userId": String, // TODO: Should this be changed to user token?
Not a token it's fine will store userId. Cleaning up comments should be fine

2024-07-21 13:46 UTC, rayasamhr commented
> Unsure about html and scss changes being included.

Got it, it seems to be from the init commit here: https://github.com/bettersg/saylah-v2/pull/10/commits/ebb6a345e021163426154c6ddf0f4a89636a811e#diff-8b29e6617f7a351aee8c778eec8c9f1411f953fecbc52c55a20ed7ff9f32f5c1

Do you want me to keep them or revert them?

2024-07-27 13:33 UTC, prakashelango commented
> > Unsure about html and scss changes being included.
> 
> Got it, it seems to be from the init commit here: [ebb6a34#diff-8b29e6617f7a351aee8c778eec8c9f1411f953fecbc52c55a20ed7ff9f32f5c1](https://github.com/bettersg/saylah-v2/commit/ebb6a345e021163426154c6ddf0f4a89636a811e#diff-8b29e6617f7a351aee8c778eec8c9f1411f953fecbc52c55a20ed7ff9f32f5c1)
> 
> Do you want me to keep them or revert them? @prakashelango

quick check comparison with dev branch or use updated code from dev should be fine

2024-08-03 06:25 UTC, prakashelango commented
> > Unsure about html and scss changes being included.
> 
> Got it, it seems to be from the init commit here: [ebb6a34#diff-8b29e6617f7a351aee8c778eec8c9f1411f953fecbc52c55a20ed7ff9f32f5c1](https://github.com/bettersg/saylah-v2/commit/ebb6a345e021163426154c6ddf0f4a89636a811e#diff-8b29e6617f7a351aee8c778eec8c9f1411f953fecbc52c55a20ed7ff9f32f5c1)
> 
> Do you want me to keep them or revert them? @prakashelango

@delose can you chime in here?

2024-08-03 06:55 UTC, merged